

"""
このファイルは定数を書いておく場所です。
"""

#画面サイズ
SCREEN_SIZE=(640,480)
#タイトル名
GAME_NAME="げんしじんのためのノベルゲーム"
#ゲーム中メッセージのフォントサイズ
GAME_MSG_FONT_SIZE=30
#ゲーム中メッセージの文字折り返し文字数
GAME_MSG_SPLIT_COUNT=19
#ゲーム中メッセージの色
GAME_MSG_COLOR=(0,0,0)
#ゲーム中メッセージの間隔
GAME_MSG_INDENT=30
#ゲーム中メッセージがどこから表示されるかの座標
GAME_MSG_POS=(10,10)
#ゲーム中メッセージの枠の大きさ
MSG_AREA_SIZE=(600,150)
#ゲーム中メッセージ枠のrootの右上xy
MSG_AREA_TOPLEFT=(20,480-(MSG_AREA_SIZE[1]+20))
#ゲーム中メッセージ枠の色
MSG_AREA_COLOR=(153,217,234)
#メッセージを喋っている人の枠のサイズ
AUTHOR_AREA_SIZE=(200,50)
#メッセージを喋っている人の枠の色
AUTHOR_AREA_COLOR=(255,255,255)
#メッセージを喋っている人の枠がどこから表示されるかの座標
AUTHOR_AREA_POS=(10,10)
#ゲーム中喋っている人の枠のrootの右上xy
AUTHOR_AREA_TOPLEFT=(20,480-(MSG_AREA_SIZE[1]+AUTHOR_AREA_SIZE[1]+20))
#立ち絵のポジション
GAME_TACHIE_POS=(400,80)
#選択画面の背景の色の濃さ
SELECTER_BACK_ALPHA=100
#選択画面のメッセージの背景の色の濃さ
SELECTER_MSG_BACK_ALPHA=200
#選択画面のメッセージの背景のサイズ
SELECTER_MSG_BACK_SIZE=(540,50)
#選択画面のメッセージの背景の場所
SELECTER_MSG_BACK_POS=(50,70)
#選択画面のメッセージの間隔
SELECTER_MSG_BACK_INDENT=80
#選択画面のメッセージの場所
SELECTER_MSG_POS=(40,7)
#セレクターのrootに対する描画位置、(0,0)推奨
SELECTER_MSG_TOPLEFT=(0,0)